---
permalink: iscsi-config-esxi/index.html 
sidebar: sidebar 
keywords: iscsi, service, storage, virtual, machine, svm, provision, lun, esx, host, computer 
summary: 此内容介绍如何在 Storage Virtual Machine 上快速设置 iSCSI 服务，配置 LUN 以及如何使用 ESX 主机计算机上的 iSCSI 启动程序使 LUN 可用。 
---
= 使用 VSC 为 ESXi 配置 iSCSI 概述
:icons: font
:imagesdir: ../media/


[role="lead"]
此内容介绍如何在 Storage Virtual Machine （ SVM ）上快速设置 iSCSI 服务，配置 LUN 以及如何使用 ESX 主机计算机上的 iSCSI 启动程序使 LUN 可用。

此内容基于以下假设：

* 您希望使用最佳实践，而不是浏览每个可用选项。
* 您不想阅读大量概念背景信息。
* 您希望使用 System Manager ，而不是 ONTAP 命令行界面或自动化脚本编写工具。
* 您希望使用适用于 ONTAP 9.7 及更早版本的 _Classic_ System Manager UI ，而不是适用于 ONTAP 9.7 及更高版本的 ONTAP System Manager UI 。
+
https://docs.netapp.com/us-en/ontap/["ONTAP System Manager 文档"]

* 您正在 ESXi 5.x 上使用原生 ESX iSCSI 软件启动程序
* 您未对 iSCSI 使用 CHAP 身份验证。
* 您正在使用支持的适用于 VMware vSphere 的 Virtual Storage Console 版本为 ESX 主机配置存储设置。
* 您的网络使用 IPv4 地址。
* 您希望使用以下任一方法为逻辑接口分配地址：
+
** 自动从您定义的子网
** 手动，使用从现有子网中选择的地址
** 手动，使用要添加到现有子网的地址


* 集群中的每个节点上至少有两个可用的高速以太网端口（至少 1 GbE ，建议使用 10 GbE ）。
+
板载 UTA2 （也称为 "`CNA` " ）端口可配置。您可以在 ONTAP 命令行界面中配置这些端口；此内容不会介绍此过程。

+
您应看到 link:https://docs.netapp.com/us-en/ontap/networking/index.html["ONTAP 9 网络管理"] 用于使用 CLI 配置以太网端口流量控制。

* 您未配置 iSCSI SAN 启动。
* 您正在通过 ESX 虚拟机管理程序为 VM 提供存储，而不是在 VM 中运行 iSCSI 启动程序。


如果这些假设与您的情况不符，您应查看以下资源：

* https://docs.netapp.com/us-en/ontap/san-admin/index.html["ONTAP 9 SAN 管理"]
* https://docs.netapp.com/us-en/ontap/san-config/index.html["ONTAP 9 SAN 配置"]
* https://docs.netapp.com/vapp-96/topic/com.netapp.doc.vsc-iag/home.html["设备管理"]
* 适用于您的 ESX 5 版本的 _VMware vSphere Storage_ （可从获取 http://www.vmware.com["VMware"]）

