---
permalink: online-help-96-97/concept_types_data_protection_relationships.html 
sidebar: sidebar 
keywords: data, protection, relationship, asynchronous, replication, type, sychronous, online, help 
summary: 根据您的数据保护和备份要求， ONTAP System Manager 提供了不同类型的保护关系，可用于保护数据免受意外，恶意或灾难导致的数据丢失的影响。 
---
= 数据保护关系的类型
:icons: font
:imagesdir: ../media/


[role="lead"]
根据您的数据保护和备份要求， ONTAP System Manager 提供了不同类型的保护关系，可用于保护数据免受意外，恶意或灾难导致的数据丢失的影响。



== 异步复制类型

* 镜像关系 *

镜像关系可提供异步灾难恢复。通过数据保护镜像关系，您可以定期在一个卷上创建数据的 Snapshot 副本，将这些 Snapshot 副本复制到通常位于另一个集群上的配对卷（目标卷），然后保留这些 Snapshot 副本。如果源卷上的数据损坏或丢失，则目标卷上的镜像副本可确保快速提供数据，并从创建最新 Snapshot 副本开始还原数据。

对于镜像关系，目标集群上运行的 ONTAP 版本必须与源集群上运行的 ONTAP 版本相同或更高。但是，版本灵活的镜像关系并不依赖于 ONTAP 版本。因此，如果目标集群运行的 ONTAP 版本高于 ONTAP 或低于源集群的 ONTAP 版本，或者 ONTAP 版本低于源集群的 ONTAP 版本，则可以与该目标集群创建版本灵活的镜像关系。

[NOTE]
====
* 要启用镜像关系，需要 SnapMirror 许可证。
* 只有 ONTAP 8.3 及更高版本才支持版本灵活的镜像关系功能。您不能与 Data ONTAP 8.3 或更早版本中的卷建立版本灵活的镜像关系。


====
* 存储关系 *

存储关系可为备份提供存储效率高的长期保留。通过存储关系，您可以将卷的选定 Snapshot 副本备份到目标卷并保留这些备份。

[NOTE]
====
要启用存储关系，需要 SnapMirror 或 SnapVault 许可证。

====
* 镜像和存储关系 *

镜像和存储关系可通过定期将数据从源卷传输到目标卷来提供数据保护，并通过创建源卷的备份来促进数据的长期保留。

[NOTE]
====
* 要启用镜像和存储关系，需要 SnapMirror 许可证。
* 只有 ONTAP 8.3.2 及更高版本才支持镜像和存储关系功能。您不能与 Data ONTAP 8.3.2 或更早版本中的卷建立镜像和存储关系。


====


== 同步复制策略（需要 SnapMirror 同步许可证）

* StrictSync*

如果初始化后复制失败， StrictSync 复制策略将对源卷实施输入 / 输出（ I/O ）限制。StrictSync 复制策略可通过确保源卷和目标卷是最新的来提供数据保护。

[NOTE]
====
* 如果目标不是数据保护优化（ DPO ），则源集群和目标集群需要 SnapMirror 许可证，而源集群则需要 SnapMirror 同步许可证。
* 如果目标为 DPO ，则源集群需要 SnapMirror 同步许可证和 SnapMirror 许可证，而目标集群则需要 DPO 许可证。


====
* 同步 *

如果初始化后复制失败，同步复制策略不会对源卷施加 I/O 限制。发生故障后， Sync 复制策略不会将数据传输到目标卷。您需要执行重新同步操作，以确保源卷和目标卷是最新的。

[NOTE]
====
* 如果目标不是数据保护优化（ DPO ），则源集群和目标集群需要 SnapMirror 许可证，而源集群则需要 SnapMirror 同步许可证。
* 如果目标为 DPO ，则源集群需要 SnapMirror 同步许可证和 SnapMirror 许可证，而目标集群则需要 DPO 许可证。


====