---
permalink: online-help-96-97/concept_license_types_entitlement_risk.html 
sidebar: sidebar 
keywords: license, types, entitlement, risk, cluster, online, help 
summary: 了解各种许可证类型以及相关授权风险有助于您管理与集群中许可证相关的风险。 
---
= 许可证类型和授权风险
:icons: font
:imagesdir: ../media/


[role="lead"]
了解各种许可证类型以及相关授权风险有助于您管理与集群中许可证相关的风险。



== 许可证类型

一个软件包可以在集群中安装以下一种或多种类型的许可证：

* 节点锁定许可证或标准许可证
+
系统会为具有特定系统序列号（也称为 _controller 序列号）的节点颁发节点锁定许可证。此许可证仅对具有匹配序列号的节点有效。

+
安装节点锁定许可证可为节点授予使用许可功能的权限。要使集群能够使用许可的功能，必须至少为一个节点授予使用此功能的许可。在没有此功能授权的节点上使用此许可功能可能不合规。

+
ONTAP 8.2 及更高版本会将 Data ONTAP 8.2 之前安装的许可证视为标准许可证。因此，在 ONTAP 8.2 及更高版本中，集群中的所有节点都会自动拥有先前许可的功能所属的软件包的标准许可证。

* 主许可证或站点许可证
+
主许可证或站点许可证不与特定系统序列号绑定。安装站点许可证时，集群中的所有节点均有权使用许可的功能。

+
如果您的集群具有主许可证，而您从集群中删除了某个节点，则该节点不会再拥有站点许可证，并且该节点不再有权使用许可的功能。如果向具有主许可证的集群添加节点，则该节点将自动获得使用站点许可证授予的功能的权限。

* 演示或临时许可证
+
演示或临时许可证将在一段时间后过期。通过此许可证，您可以在不购买授权的情况下尝试某些软件功能。临时许可证是一种集群范围的许可证，不与节点的特定序列号绑定。

+
如果您的集群具有某个软件包的临时许可证，而您从集群中删除了某个节点，则该节点不会附带评估许可证。

* 容量许可证（仅限 ONTAP Select 和 FabricPool ）
+
ONTAP Select 实例将根据用户要管理的数据量获得许可。例如，用户可以购买 10 TB 容量许可证，以使 ONTAP Select 能够管理多达 10 TB 的数据。如果连接到系统的存储容量超过 ONTAP Select 的管理权限，则 ONTAP Select 将无法运行。默认情况下，在购买并安装容量许可证（例如 5 TB 容量许可证， 10 TB 容量许可证等）之前，可以附加到 ONTAP Select 实例的最大存储容量为 2 TB 。

+
从 ONTAP 9.2 开始，启用了 FabricPool 的聚合要求在第三方存储层（例如 AWS ）上使用容量许可证。FabricPool 容量许可证用于定义可存储在云层存储中的数据量。





== 授权风险

由于节点锁定许可证的安装不一致，因此会产生授权风险。如果节点锁定许可证安装在所有节点上，则不存在授权风险。

授权风险级别可以是高风险，中等风险，无风险或未知风险，具体取决于特定条件：

* 高风险
+
** 如果某个特定节点上使用了，但未在该节点上安装节点锁定许可证
** 如果集群上安装的演示许可证到期，并且任何节点上都使用了


+
[NOTE]
====
如果在集群上安装了站点许可证，则授权风险绝不会很高。

====
* 中等风险
+
如果未安装站点许可证，并且集群中的节点上安装的节点锁定许可证不一致

* 无风险
+
如果在所有节点上安装了节点锁定许可证，或者在集群上安装了站点许可证，则无论使用情况如何，均不存在授权风险。

* 未知
+
如果 API 有时无法检索与集群或集群中节点相关的授权风险相关的数据，则风险未知。


