---
permalink: online-help-96-97/reference_nvme_namespaces_window.html 
sidebar: sidebar 
keywords: nvme, namespace, command, button, subsystems, protocol, online, help 
summary: 您可以使用 NVMe 命名空间窗口设置和管理 NVMe 协议的命名空间以及关联子系统。您可以使用命名空间路径搜索现有命名空间。 
---
= NVMe 命名空间窗口
:icons: font
:imagesdir: ../media/


[role="lead"]
您可以使用 NVMe 命名空间窗口设置和管理 NVMe 协议的命名空间以及关联子系统。您可以使用命名空间路径搜索现有命名空间。



== 命令按钮

* * 创建 * 。
+
打开 NVMe 命名空间创建对话框，在此可以设置新命名空间并将其映射到 NVMe 子系统。

* * 编辑 * 。
+
用于编辑命名空间映射。

* * 删除 *
+
删除选定命名空间。

* * 更多操作 *
+
用于创建选定命名空间的克隆，该克隆可与现有子系统关联，也可以选择不将其映射到子系统。

* * 刷新 *
+
更新窗口中的信息。





== NVMe 列表

* * 状态 *
+
显示命名空间是联机还是脱机。

* * 命名空间路径 *
+
以 ` /vol/volume'/file` 格式指向新命名空间的路径。命名空间路径是一个可单击的链接。单击此链接可转到命名空间详细信息页面。

* * NVMe 子系统 *
+
连接到命名空间的子系统的名称。如果未连接任何子系统，则此列的值显示为 `None` 。您可以通过筛选此列中的 NVMe 子系统包含 `None` 来查看未映射的命名空间列表。

* * SVM*
+
用于创建命名空间的 SVM 名称。SVM 名称是一个可单击的链接。单击此链接将转到现有 SVM 信息板页面。

+
从 ONTAP 9.5 开始，必须为与 SVM 关联的 HA 对中的每个节点至少配置一个 NVMe LIF 。您最多可以为对中的每个节点创建两个 NVMe LIF 。

* * 命名空间 ID*
+
控制器用于提供对命名空间的访问的唯一标识符。这不是用户输入；它是在创建新命名空间时由系统生成的。

* * 总空间 *
+
显示命名空间的总大小。

* * 已用空间 *
+
显示命名空间中的已用空间量。

* * 已用 % *
+
显示命名空间中使用的空间量（以百分比表示）。此字段的值是使用总空间和已用空间计算得出的。





== 详细信息区域

您可以选择一个命名空间以查看有关选定命名空间的信息。在此区域中，您还可以编辑，删除或克隆命名空间。

* "* 概述 * 选项卡 "
+
显示有关选定命名空间的常规信息，并以图形方式显示命名空间的空间分配和命名空间的性能。

+
在概述选项卡中， SVM 和卷名称是可单击的链接。单击此链接将分别转到 SVM 和卷页面。主机数可以是一个或多个；默认情况下，显示两个主机名。如果显示的主机名超过两个，则可以单击一个链接以访问其他主机。

+
" 概述 " 选项卡还会显示一个空间图表，其中显示了命名空间的总空间和已用空间详细信息，并显示了一个性能图表，其中显示了延迟， IOPS 和吞吐量等详细信息。

* * 状态 *
+
命名空间的状态；值可以是联机或脱机。

* * 主机 NQN*
+
主机 NVMe 限定名称（ NQN ）用于唯一描述主机，以便进行标识和身份验证。此字段可以接受以逗号分隔的 NVMe 限定名称（ NQN ）值。主机 NQN 以 `nqn` 开头，其余验证与启动程序限定名称（ IQN ）相同。

* * 主机 OS*
+
命名空间的主机操作系统： Hyper-V ， Linux ， VMware ， Windows 或 Xen 。

* * 卷 *
+
显示托管命名空间的卷名称。

* * 只读 *
+
显示命名空间是否为只读。

* * 节点 *
+
拥有命名空间的节点。

* * 块大小 *
+
存储块的大小。

* * 无法访问还原 *
+
如果取消映射子系统失败，并且仍保留部分数据，则无法还原未映射的命名空间。


