---
permalink: online-help-96-97/reference_nvme_subsystems_window.html 
sidebar: sidebar 
keywords: nvme, subsystems, window, table, toolbar, online, help, cluster 
summary: 默认情况下， NVMe 子系统窗口会显示集群中 NVMe 子系统的清单列表。您可以对列表进行筛选，以便仅显示特定于 SVM 的子系统。此窗口还可用于创建，编辑或删除 NVMe 子系统。您可以通过选择存储 NVMe 子系统来访问此窗口。 
---
= NVMe 子系统窗口
:icons: font
:imagesdir: ../media/


[role="lead"]
默认情况下， NVMe 子系统窗口会显示集群中 NVMe 子系统的清单列表。您可以对列表进行筛选，以便仅显示特定于 SVM 的子系统。此窗口还可用于创建，编辑或删除 NVMe 子系统。您可以通过选择 * 存储 * > * NVMe* > * 子系统 * 来访问此窗口。

* <<GUID-1E417C67-1F31-4FA5-AAA7-2D5BB298C6AB,NVMe 子系统表>>
* <<SECTION_819274C0AB2341B0915167A78A41F1D8,工具栏>>




== NVMe 子系统表

NVMe 子系统表列出了集群中 NVMe 子系统的清单。您可以使用 * SVM* 字段中的下拉菜单选择一个 SVM 以仅显示与该 SVM 关联的 NVMe 子系统来细化此列表。通过 * 搜索 * 字段和 * 筛选 * 下拉菜单，您可以进一步自定义此列表。

NVMe 子系统表包含以下列：

* * （复选框） *
+
用于指定要对其执行操作的子系统。

+
单击复选框以选择子系统，然后在工具栏中单击要执行的操作。

* * 名称 *
+
显示子系统的名称。

+
您可以通过在 * 搜索 * 字段中输入子系统名称来搜索子系统。

* * 主机 OS*
+
显示与子系统关联的主机操作系统的名称。

* * 主机 NQN*
+
显示连接到控制器的 NVMe 限定名称（ NQN ）。如果显示多个 NQN ，则它们以逗号分隔。

* * 关联的 NVMe 命名空间 *
+
显示与子系统关联的 NVM 命名空间的数量。您可以将鼠标悬停在该数字上以显示关联的命名空间路径。单击某个路径以显示命名空间详细信息窗口。





== 工具栏

工具栏位于列标题上方。您可以使用工具栏中的字段和按钮执行各种操作。

* * 搜索 *
+
用于搜索 * 名称 * 列中可能存在的值。

* * 筛选 *
+
用于从下拉菜单中选择各种筛选列表的方法。

* * 创建 * 。
+
打开创建 NVMe 子系统对话框，在此可以创建 NVMe 子系统。

* * 编辑 * 。
+
打开编辑 NVMe 子系统对话框，在此可以编辑现有 NVMe 子系统。

* * 删除 *
+
打开删除 NVMe 子系统确认对话框，在此可以删除现有 NVMe 子系统。


