---
permalink: online-help-96-97/reference_shares_window.html 
sidebar: sidebar 
keywords: command, buttons, shares, window, online, help 
summary: 您可以使用共享窗口管理共享并查看有关共享的信息。 
---
= 共享窗口
:icons: font
:imagesdir: ../media/


[role="lead"]
您可以使用共享窗口管理共享并查看有关共享的信息。



== 命令按钮

* * 创建共享 *
+
打开创建共享对话框，在此可以创建共享。

* * 创建主目录 *
+
打开创建主目录共享对话框，在此可以创建新的主目录共享。

* * 编辑 * 。
+
打开编辑设置对话框，在此可以修改选定共享的属性。

* * 停止共享 *
+
停止共享选定对象。

* * 刷新 *
+
更新窗口中的信息。





== 共享列表

共享列表显示每个共享的名称和路径。

* * 共享名称 *
+
显示共享的名称。

* * 路径 *
+
显示共享的现有文件夹， qtree 或卷的完整路径名。路径分隔符可以是反斜线或正斜线，但 ONTAP 会将所有路径分隔符显示为正斜线。

* * 主目录 *
+
显示主目录共享的名称。

* * 注释 *
+
显示共享的其他说明（如果有）。

* * 持续可用共享 *
+
显示是否为共享启用了持续可用性。从 System Manager 9.6 开始， FlexGroup 卷支持持续可用性。





== 详细信息区域

共享列表下方的区域显示每个共享的共享属性和访问权限。

* * 属性 *
+
** Name
+
显示共享的名称。

** 机会锁状态
+
指定共享是否使用机会锁（ oplock ）。

** 可浏览
+
指定 Windows 客户端是否可以浏览共享。

** 显示 Snapshot
+
指定客户端是否可以查看 Snapshot 副本。

** 持续可用的共享
+
指定是启用还是禁用共享以实现持续可用性。从 System Manager 9.6 开始， FlexGroup 卷支持持续可用性。

** 基于访问的枚举
+
指定共享上是启用还是禁用基于访问的枚举（ ABE ）。

** BranchCache
+
指定共享上是启用还是禁用 BranchCache 。

** SMB 加密
+
指定是在 Storage Virtual Machine （ SVM ）级别还是在共享级别启用使用 SMB 3.0 的数据加密。如果在 SVM 级别启用了 SMB 加密，则 SMB 加密适用于所有共享，并且此值显示为已启用（在 SVM 级别）。

** 先前版本
+
指定是否可以从客户端查看和还原先前的版本。



* * 共享访问控制 *
+
显示共享的域用户，域组，本地用户和本地组的访问权限。



* 相关信息 *

xref:task_creating_cifs_share.adoc[创建 CIFS 共享]

xref:task_stopping_share_access.adoc[正在停止共享访问]

xref:task_editing_share_settings.adoc[编辑共享设置]
