---
permalink: online-help-96-97/reference_svm_relationships_window.html 
sidebar: sidebar 
keywords: svm, relationship, window, command, button, online, help, mirror 
summary: 您可以使用 SVM 关系窗口创建和管理 SVM 之间的镜像关系以及镜像和存储关系。 
---
= SVM 关系窗口
:icons: font
:imagesdir: ../media/


[role="lead"]
您可以使用 SVM 关系窗口创建和管理 SVM 之间的镜像关系以及镜像和存储关系。



== 命令按钮

* * 创建 * 。
+
打开 SVM 灾难恢复页面，在此可以从目标卷创建镜像关系或镜像和存储关系。

* * 编辑 * 。
+
用于编辑关系的计划和策略。

+
对于镜像和存储关系或版本灵活的镜像关系，您可以通过修改策略类型来修改关系类型。

* * 删除 *
+
用于删除关系。

* * 操作 *
+
提供了以下选项：

+
** * 初始化 *
+
用于初始化 SVM 关系以执行从源 SVM 到目标 SVM 的基线传输。

** * 更新 *
+
用于将数据从源 SVM 更新到目标 SVM 。

** * 激活目标 SVM*
+
用于激活目标 SVM 。

** * 从源 SVM* 重新同步
+
用于对已断开的关系启动重新同步。

** * 从目标 SVM 重新同步（反向重新同步） *
+
用于重新同步从目标 SVM 到源 SVM 的关系。

** * 重新激活源 SVM*
+
用于重新激活源 SVM 。



* * 刷新 *
+
更新窗口中的信息。





== SVM 关系列表

* * 源 Storage Virtual Machine*
+
显示包含在关系中镜像和存储数据的卷的 SVM 。

* * 目标 Storage Virtual Machine*
+
显示包含在关系中将数据镜像和存储到的卷的 SVM 。

* * 运行状况良好 *
+
显示关系是否运行正常。

* * 关系状态 *
+
显示关系的状态，例如已执行 Snapmirrored ，未初始化或已断开。

* * 传输状态 *
+
显示关系的状态。

* * 关系类型 *
+
显示关系的类型，例如镜像或镜像和存储。

* * 滞后时间 *
+
滞后时间是指当前时间与已成功传输到目标系统的最后一个 Snapshot 副本的时间戳之间的差值。除非源系统和目标系统上的时钟未同步，否则滞后时间始终至少与上次成功传输的持续时间相同。时区差异会自动计算为滞后时间。

* * 策略名称 *
+
显示分配给关系的策略的名称。

* * 策略类型 *
+
显示分配给关系的策略类型。策略类型可以是 StrictSync ， Sync ，异步镜像，异步存储或异步镜像存储。





== 详细信息区域

* * 详细信息选项卡 *
+
显示有关选定关系的常规信息，例如源集群和目标集群，与 SVM 关联的保护关系，数据传输速率，关系状态，网络压缩率详细信息，数据传输状态，当前数据传输类型，上次数据传输类型， 最新 Snapshot 副本，最新 Snapshot 副本的时间戳，身份保留的状态以及受保护的卷数。

* * 策略详细信息选项卡 *
+
显示有关分配给选定保护关系的策略的详细信息。


