---
permalink: online-help-96-97/reference_cluster_peers_window.html 
sidebar: sidebar 
keywords: cluster, peer, window, command, button, online, help 
summary: 您可以使用集群对等方窗口管理对等集群关系，从而可以将数据从一个集群移动到另一个集群。 
---
= 集群对等方窗口
:icons: font
:imagesdir: ../media/


[role="lead"]
您可以使用集群对等方窗口管理对等集群关系，从而可以将数据从一个集群移动到另一个集群。



== 命令按钮

* * 创建 * 。
+
打开创建集群对等对话框，在此可以创建与远程集群的关系。

* * 编辑 * 。
+
显示一个下拉菜单，其中包含以下选项：

+
** * 本地集群密码短语 *
+
打开编辑本地集群密码短语对话框，在此可以输入新密码短语以验证本地集群。

** * 对等集群网络参数 *
+
打开编辑对等集群网络参数对话框，在此可以修改 IP 空间以及添加或删除集群间 LIF IP 地址。

+
您可以添加多个 IP 地址，以逗号分隔。

** * 更改加密 *
+
打开选定对等集群的更改加密对话框。在更改对等关系的加密时，您可以生成新的密码短语，也可以提供已在远程对等集群上生成的密码短语。

+
如果加密状态为 "`N/A` " ，则此操作不可用。



* * 删除 *
+
打开删除集群对等关系对话框，在此可以删除选定的对等集群关系。

* * 刷新 *
+
更新窗口中的信息。

* * 管理 SVM 权限 *
+
允许 SVM 自动接受 SVM 对等请求。

* * 生成对等密码短语 *
+
用于通过指定 IP 空间，设置密码短语有效期限以及指定为其授予权限的 SVM 来为本地集群 IP 空间生成密码短语。

+
您可以在远程集群中使用相同的密码短语建立对等关系。





== 对等集群列表

* * 对等集群 *
+
指定关系中对等集群的名称。

* * 可用性 *
+
指定对等集群是否可用于通信。

* * 身份验证状态 *
+
指定对等集群是否经过身份验证。

* * 本地集群 IP 空间 *
+
显示与本地集群对等关系关联的 IP 空间。

* * 对等集群集群间 IP 地址 *
+
显示与集群间对等关系关联的 IP 地址。

* * 上次更新时间 *
+
显示上次修改对等集群的时间。

* * 加密 *
+
显示对等关系的加密状态。

+
[NOTE]
====
从 System Manager 9.6 开始，当您在两个集群之间建立对等关系时，对等关系默认处于加密状态

====
+
** * 不适用 * ：加密不适用于此关系。
** * 无 * ：对等关系未加密。
** * TLS PSK* ：对等关系已加密。



