---
permalink: online-help-96-97/reference_name_mapping_window.html 
sidebar: sidebar 
keywords: name, map, window, command, button, online, help, group 
summary: 您可以使用名称映射窗口指定名称映射条目以映射不同平台的用户。 
---
= 名称映射窗口
:icons: font
:imagesdir: ../media/


[role="lead"]
您可以使用名称映射窗口指定名称映射条目以映射不同平台的用户。



== 名称映射

您可以创建并使用名称映射将 UNIX 用户映射到 Windows 用户，将 Windows 用户映射到 UNIX 用户或将 Kerberos 用户映射到 UNIX 用户。



== 命令按钮

* * 添加 * 。
+
打开添加名称映射条目对话框，在此可以在 Storage Virtual Machine （ SVM ）上创建名称映射。

* * 编辑 * 。
+
打开编辑名称映射条目对话框，在此可以编辑 SVM 上的名称映射。

* * 删除 *
+
打开删除名称映射条目对话框，在此可以删除名称映射条目。

* * 交换 *
+
打开交换名称映射条目对话框，在此可以互换两个选定名称映射条目的位置。

* * 刷新 *
+
更新窗口中的信息。





== 名称映射列表

* * 位置 *
+
指定名称映射在优先级列表中的位置。名称映射在优先级列表中的应用顺序相同。

* * 模式 *
+
指定必须匹配的用户名模式。

* * 替换 *
+
指定用户名的替换模式。

* * 方向 *
+
指定名称映射的方向。可能的值包括：用于 Kerberos 到 UNIX 名称映射的 KRB_UNIX ，用于 Windows 到 UNIX 名称映射的 WIN_UNIX 以及用于 UNIX 到 Windows 名称映射的 UNIX_WIN 。





== 命令按钮

* * 添加 * 。
+
打开添加组映射条目对话框，在此可以在 SVM 上创建组映射。

* * 编辑 * 。
+
打开编辑组映射条目对话框，在此可以编辑 SVM 上的组映射。

* * 删除 *
+
打开删除组映射条目对话框，在此可以删除组映射条目。

* * 交换 *
+
打开交换组映射条目对话框，在此可以交换两个选定组映射条目的位置。

* * 刷新 *
+
更新窗口中的信息。





== 组映射列表

* * 位置 *
+
指定组映射在优先级列表中的位置。组映射将按照优先级列表中的顺序进行应用。

* * 模式 *
+
指定必须匹配的用户名模式。

* * 替换 *
+
指定用户名的替换模式。

* * 方向 *
+
指定组映射的方向。可能的值包括： Kerberos 到 UNIX 组映射为 `krf_unix` ， Windows 到 UNIX 组映射为 `win_unix` ， UNIX 到 Windows 组映射为 `unix_win` 。


