---
permalink: online-help-96-97/task_creating_mirror_relationship_from_destination_svm.html 
sidebar: sidebar 
keywords: create, mirror, relationship, destination, svm, online, help, system, manager 
summary: 您可以使用 ONTAP 系统管理器从目标 Storage Virtual Machine （ SVM ）创建镜像关系，并为此镜像关系分配策略和计划。如果源卷上的数据损坏或丢失，镜像副本可以快速提供数据。 
---
= 从目标 SVM 创建镜像关系
:icons: font
:imagesdir: ../media/


[role="lead"]
您可以使用 ONTAP 系统管理器从目标 Storage Virtual Machine （ SVM ）创建镜像关系，并为此镜像关系分配策略和计划。如果源卷上的数据损坏或丢失，镜像副本可以快速提供数据。

.开始之前
* 源集群必须运行 ONTAP 8.2.2 或更高版本。
* 必须在源集群和目标集群上启用 SnapMirror 许可证。
+
[NOTE]
====
对于某些平台，如果目标集群启用了 SnapMirror 许可证和数据保护优化（ DPO ）许可证，则源集群不必启用 SnapMirror 许可证。

====
* 在镜像卷时，如果选择 SnapLock 卷作为源卷，则必须在目标集群上安装 SnapMirror 许可证和 SnapLock 许可证。
* 源集群和目标集群之间的对等关系必须运行正常。
* 目标 SVM 必须具有可用空间。
* 必须存在读 / 写（ rw ）类型的源卷。
* FlexVol 卷必须处于联机状态，并且类型必须为读 / 写。
* SnapLock 聚合类型必须相同。
* 如果要从运行 ONTAP 9.2 或更早版本的集群连接到启用了安全断言标记语言（ SAML ）身份验证的远程集群，则必须在远程集群上启用基于密码的身份验证。


.关于此任务
* System Manager 不支持级联关系。
+
例如，关系中的目标卷不能是另一关系中的源卷。

* 您不能在 MetroCluster 配置中 sync-source SVM 和 sync-destination SVM 之间创建镜像关系。
* 您可以在 MetroCluster 配置中 sync-source SVM 之间创建镜像关系。
* 您可以创建从 sync-source SVM 上的卷到提供数据的 SVM 上的卷的镜像关系。
* 您可以创建从提供数据的 SVM 上的卷到 sync-source SVM 上的数据保护（ DP ）卷的镜像关系。
* 您只能在相同类型的 SnapLock 卷之间创建镜像关系。
+
例如，如果源卷是 SnapLock Enterprise 卷，则目标卷也必须是 SnapLock Enterprise 卷。您必须确保目标 SVM 具有相同 SnapLock 类型的聚合。

* 为镜像关系创建的目标卷不会进行精简配置。
* 一次选择最多可以保护 25 个卷。
* 如果目标集群运行的 ONTAP 版本早于源集群运行的 ONTAP 版本，则无法在 SnapLock 卷之间创建镜像关系。


.步骤
. 单击 * 保护 * > * 卷关系 * 。
. 在 * 卷关系 * 窗口中，单击 * 创建 * 。
. 在 * 浏览 SVM* 对话框中，为目标卷选择一个 SVM 。
. 在 * 创建保护关系 * 对话框中，从 * 关系类型 * 下拉列表中选择 * 镜像 * 。
. 指定集群， SVM 和源卷。
+
如果指定集群运行的 ONTAP 软件版本早于 ONTAP 9.3 ，则仅会列出对等 SVM 。如果指定集群运行的是 ONTAP 9.3 或更高版本，则会列出对等 SVM 和允许的 SVM 。

. 对于 FlexVol 卷，请指定卷名称后缀。
+
卷名称后缀会附加到源卷名称中，以生成目标卷名称。

. 单击 * 浏览 * ，然后更改镜像策略。
. 从现有计划列表中为此关系选择一个计划。
. 选择 * 初始化关系 * 以初始化镜像关系。
. 启用启用启用了 FabricPool 的聚合，然后选择适当的分层策略。
. 单击 * 创建 * 。


如果选择创建目标卷，则会创建类型为 _dp_ 的目标卷，并将语言属性设置为与源卷的语言属性匹配。

在源卷和目标卷之间创建镜像关系。如果选择初始化此关系，则基本 Snapshot 副本将传输到目标卷。

* 相关信息 *

xref:reference_protection_window.adoc[保护窗口]
