---
permalink: online-help-96-97/task_creating_local_user_group.html 
sidebar: sidebar 
keywords: create, local, window, group, online, help, system, manager 
summary: 您可以使用 System Manager 创建本地 Windows 组，这些组可用于授权通过 SMB 连接访问 Storage Virtual Machine （ SVM ）中包含的数据。您还可以分配权限，以定义组成员在执行管理活动时所拥有的用户权限或功能。 
---
= 创建本地 Windows 组
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
您可以使用 System Manager 创建本地 Windows 组，这些组可用于授权通过 SMB 连接访问 Storage Virtual Machine （ SVM ）中包含的数据。您还可以分配权限，以定义组成员在执行管理活动时所拥有的用户权限或功能。

必须为 SVM 配置 CIFS 服务器。

.关于此任务
* 您可以指定包含或不包含本地域名的组名称。
+
本地域是 SVM 的 CIFS 服务器的名称。例如，如果 SVM 的 CIFS 服务器名称是 "`CIFS_Server` " ，而您要创建 "`engineering` " 组，则可以指定 "`engineering` " 或 "`CIFS_SERVER\engineering` " 作为组名称。

+
在组名称中使用本地域时，应遵循以下规则：

+
** 您只能为将组应用到的 SVM 指定本地域名。
+
例如，如果本地 CIFS 服务器名称是 "`CIFS_SERVER` " ，则不能指定 "`corp_SERVER\group1` " 作为组名称。

** 您不能在组名称中使用 "`BUILTIN` " 作为本地域。
+
例如，您不能创建名称为 "`BUILTIN\group1` " 的组。

** 您不能在组名称中使用 Active Directory 域作为本地域。
+
例如，您不能创建名为 "`AD_DOM\group1` " 的组，其中 "`AD_DOM` " 是 Active Directory 域的名称。



* 您不能使用已存在的组名称。
* 指定的组名称必须满足以下要求：
+
** 不得超过 256 个字符
** 不得在句点后结束
** 不得包含逗号
** 不得包含以下任何可打印字符： " / \ [ ] ： | < > + = ；？* @
** 不得包含 ASCII 范围 1 到 31 的字符，这些字符不可打印




.步骤
. 单击 * 存储 * > * SVMs * 。
. 选择 SVM ，然后单击 * SVM 设置 * 。
. 在 * 主机用户和组 * 窗格中，单击 * Windows * 。
. 在 * 组 * 选项卡中，单击 * 创建 * 。
. 在 * 创建组 * 对话框中，指定组的名称以及有助于标识新组的问题描述。
. 为组分配一组权限。
+
您可以从一组预定义的受支持权限中选择权限。

. 单击 * 添加 * 将用户添加到组。
. 在 * 将成员添加到组 * 对话框中，执行以下操作之一：
+
** 指定要添加到特定本地组的 Active Directory 用户或 Active Directory 组。
** 从 SVM 中的可用本地用户列表中选择用户。
** 单击 * 确定 * 。


. 单击 * 创建 * 。


此时将创建本地 Windows 组，并将其列在组窗口中。

* 相关信息 *

xref:reference_windows_window.adoc[Windows 窗口]
