---
permalink: online-help-96-97/task_creating_mirror_vault_relationship_from_destination_svm.html 
sidebar: sidebar 
keywords: system, manager, create, mirror, vault, relationship, destination, svm, online, help 
summary: 您可以使用 System Manager 从目标 Storage Virtual Machine （ SVM ）创建镜像和存储关系。通过创建此关系，您可以定期将数据从源卷传输到目标卷，从而更好地保护数据。此外，您还可以通过创建源卷的备份来长期保留数据。 
---
= 从目标 SVM 创建镜像和存储关系
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
您可以使用 System Manager 从目标 Storage Virtual Machine （ SVM ）创建镜像和存储关系。通过创建此关系，您可以定期将数据从源卷传输到目标卷，从而更好地保护数据。此外，您还可以通过创建源卷的备份来长期保留数据。

.开始之前
* 目标集群必须运行 ONTAP 8.3.2 或更高版本。
* 必须在源集群和目标集群上启用 SnapMirror 许可证。
+
[NOTE]
====
对于某些平台，如果目标集群启用了 SnapMirror 许可证和数据保护优化（ DPO ）许可证，则源集群不必启用 SnapMirror 许可证。

====
* 源集群和目标集群之间的对等关系必须运行正常。
* 目标 SVM 必须具有可用空间。
* 源聚合和目标聚合必须是 64 位聚合。
* 必须已存在读 / 写（ rw ）类型的源卷。
* SnapLock 聚合类型必须相同。
* 如果要从运行 ONTAP 9.2 或更早版本的集群连接到启用了 SAML 身份验证的远程集群，则必须在远程集群上启用基于密码的身份验证。


.关于此任务
* System Manager 不支持级联关系。
+
例如，关系中的目标卷不能是另一关系中的源卷。

* 您不能在 MetroCluster 配置中 sync-source SVM 和 sync-destination SVM 之间创建镜像和存储关系。
* 您可以在 MetroCluster 配置中 sync-source SVM 之间创建镜像和存储关系。
* 您可以创建从 sync-source SVM 上的卷到提供数据的 SVM 上的卷的镜像和存储关系。
* 您可以创建从提供数据的 SVM 上的卷到 sync-source SVM 上的 DP 卷的镜像和存储关系。
* 一次选择最多可以保护 25 个卷。


.步骤
. 单击 * 保护 * > * 卷关系 * 。
. 在 * 关系 * 窗口中，单击 * 创建 * 。
. 在 * 浏览 SVM* 对话框中，为目标卷选择一个 SVM 。
. 在 * 创建保护关系 * 对话框中，从 * 关系类型 * 下拉列表中选择 * 镜像和存储 * 。
. 指定集群， SVM 和源卷。
+
如果指定集群运行的 ONTAP 软件版本早于 ONTAP 9.3 ，则仅会列出对等 SVM 。如果指定集群运行的是 ONTAP 9.3 或更高版本，则会列出对等 SVM 和允许的 SVM 。

. 输入卷名称后缀。
+
卷名称后缀会附加到源卷名称中，以生成目标卷名称。

. 单击 * 浏览 * ，然后更改镜像和存储策略。
+
您可以选择与附加到源卷的 Snapshot 策略具有最大匹配标签数的策略。

. 从现有计划列表中为此关系选择一个计划。
. 选择 * 初始化关系 * 以初始化此关系。
. 启用启用启用了 FabricPool 的聚合，然后选择适当的分层策略。
. 单击 * 验证 * 以验证选定卷是否具有匹配标签。
. 单击 * 创建 * 。

