---
permalink: online-help-96-97/task_changing_peering_encryption_status.html 
sidebar: sidebar 
keywords: change, peer, encryption, status, system, manager, cluster, online, help 
summary: 您可以使用 System Manager 更改选定集群的对等加密状态。 
---
= 更改对等加密状态
:icons: font
:imagesdir: ../media/


[role="lead"]
您可以使用 System Manager 更改选定集群的对等加密状态。

加密状态可以是已启用或已禁用。您可以通过选择 * 更改加密 * 将状态从已启用更改为已禁用或从已禁用更改为已启用。

.步骤
. 单击 * 配置 * > * 集群对等方 * 。
. 选择对等集群，然后单击 * 编辑 *
+
此时将显示下拉菜单。

. 单击 * 更改加密 * 。
+
如果加密状态为 "`N/A` " ，则此操作不可用。

+
此时将显示更改加密对话框窗口。切换按钮用于指示当前加密状态。

. 滑动切换按钮以更改对等加密状态，然后继续。
+
** 如果当前加密状态为 "`none` " ，则可以滑动切换按钮将此状态更改为 "`tls_psk` " 来启用加密。
** 如果当前加密状态为 "`tls_psk` " ，则可以滑动切换按钮将状态更改为 "`none` " 来禁用加密。


. 启用或禁用对等加密后，您可以生成一个新密码短语并在对等集群上提供该密码短语，也可以应用已在对等集群上生成的现有密码短语。
+
[NOTE]
====
如果本地站点上使用的密码短语与远程站点上使用的密码短语不匹配，则集群对等关系将无法正常运行。

====
+
选择以下选项之一：

+
** * 生成密码短语 * ：继续执行步骤 <<STEP_1ABAF15926174E709CA59192E200ABE3,#stef_1ABA15926174E709CA59192E200ABe3>>。
** * 已有密码短语 * ：继续执行步骤 <<STEP_2EFD822431974811AD2260C3F31DC977,#stef_2EFD822431974811AD2260C3F31DC977>>。


. 如果选择 * 生成密码短语 * ，请填写必要的字段：
+
** * IP 空间 * ：从下拉菜单中选择 IP 空间。
** * 密码短语有效期 * ：从下拉菜单中选择希望密码短语有效的持续时间。
** * SVM 权限 * ：选择以下选项之一：
+
*** * 所有 SVM* 以指示允许所有 SVM 访问集群。
*** * 选定 SVM* 以指示允许访问集群的特定 SVM 。在要指定的字段中突出显示 SVM 名称。




. 如果远程集群的有效集群版本早于 ONTAP 9.6 ，请选中此复选框。否则，将无法生成密码短语。
. 单击 * 应用 * 。
+
系统将为此关系生成密码短语并显示此密码短语。您可以复制密码短语或通过电子邮件发送密码短语。

+
在选定密码短语有效期内，本地集群的身份验证状态将显示为 `ok_and_offer` ，直到您在远程集群上提供密码短语为止。

. 如果您已在远程集群中生成新密码短语，请执行以下子步骤：
+
.. 单击 * 已有密码短语 * 。
.. 在 * 密码短语 * 字段中输入在远程集群中生成的同一密码短语。
.. 单击 * 应用 * 。



