---
permalink: online-help-96-97/task_configuring_administration_details_svm.html 
sidebar: sidebar 
keywords: storage, virtual, machine, configure, administration, details, svm, online, help, system, manager 
summary: 您可以使用 System Manager 快速配置 Storage Virtual Machine （ SVM ）的管理详细信息。您可以选择将 SVM 的管理委派给 SVM 管理员。 
---
= 配置 SVM 的管理详细信息
:icons: font
:imagesdir: ../media/


[role="lead"]
您可以使用 System Manager 快速配置存储虚拟机（ SVM ）的管理详细信息。您可以选择将 SVM 的管理委派给 SVM 管理员。

作为 SVM 管理员，您不能使用 System Manager 管理委派的 SVM 。您只能使用命令行界面（ CLI ）来管理 SVMsonly 。

.步骤
. 单击 * 配置 * > * 集群 * > * 配置更新 * 。
. 在 * SVM* 选项卡中，选择节点，然后单击 * 配置管理详细信息 * 。
. 在 * 管理员详细信息 * 部分中，为 `vsadmin` 用户帐户设置密码。
. 如果要使用专用 LIF 进行 SVM 管理，请选择 * 为 SVM 管理创建 LIF * ，然后指定网络详细信息。
+
SAN 协议需要一个专用的 SVM 管理 LIF ，其中数据和管理协议不能共享同一个 LIF 。只能在数据端口上创建 SVM 管理 LIF 。

. 指定网络详细信息：
+
|===
| 如果您要 ... | 那么 ... 


 a| 
使用子网指定 IP 地址
 a| 
.. 选择 * 使用子网 * 。
.. 在添加详细信息对话框中，选择必须从中分配 IP 地址的子网。
+
对于集群间 LIF ，仅显示与选定 IP 空间关联的子网。

.. 如果要为接口分配特定 IP 地址，请选择 * 使用特定 IP 地址 * ，然后键入 IP 地址。
+
如果您指定的 IP 地址尚未位于子网范围内，则会将该 IP 地址添加到子网中。

.. 单击 * 确定 * 。




 a| 
手动指定 IP 地址，而不使用子网
 a| 
.. 选择 * 不使用子网 * 。
.. 在添加详细信息对话框中，执行以下步骤：
+
... 指定 IP 地址和网络掩码或前缀。
... 可选：指定网关。
+
目标字段将根据 IP 地址系列使用默认值进行填充。

... 如果不需要默认值，请指定新的目标值。如果路由不存在，则会根据网关和目标自动创建新路由。


.. 单击 * 确定 * 。


|===
. 指定用于创建数据 LIF 的端口：
+
.. 单击 * 浏览 * 。
.. 在 * 选择网络端口或适配器 * 对话框中，选择一个端口，然后单击 * 确定 * 。



