---
permalink: online-help-96-97/task_managing_svm_relationships.html 
sidebar: sidebar 
keywords: system, manager, manage, svm, online, help, relationship 
summary: 您可以使用 System Manager 对 SVM 关系执行各种操作，例如初始化 SVM 关系，更新 SVM 关系，激活目标 SVM ，从源 SVM 重新同步数据，从目标 SVM 重新同步数据以及重新激活源 SVM 。 
---
= 管理 SVM 关系
:icons: font
:imagesdir: ../media/


[role="lead"]
您可以使用 System Manager 对 SVM 关系执行各种操作，例如初始化 SVM 关系，更新 SVM 关系，激活目标 SVM ，从源 SVM 重新同步数据，从目标 SVM 重新同步数据以及重新激活源 SVM 。

.开始之前
* 要初始化 SVM 关系，源集群和目标集群必须处于运行状况良好的对等关系中。
* 要更新 SVM 关系，必须初始化 SVM 关系并使其处于 Snapmirrored 状态。
* 要重新激活源 SVM ，必须已执行从目标 SVM 重新同步数据（反向重新同步）操作。
* 如果在创建 SVM 关系时选择了复制源 SVM 配置的选项，则要激活 SVM 关系，必须停止源 SVM 。
* 必须在源集群和目标集群上启用 SnapMirror 许可证。
* 源集群和目标集群之间的对等关系必须运行正常。
* 目标集群必须具有可用空间。
* 源 SVM 必须具有 SVM 对等权限。
* 您必须中断 SVM 关系才能激活目标 SVM ，从源 SVM 重新同步，从目标 SVM 重新同步（反向重新同步）以及重新激活源 SVM 。
* 要重新激活源 SVM ， SVM 反向关系必须存在且处于 Snapmirrored 状态。


.步骤
. 单击 * 保护 * > * SVM 关系 * 。
. 选择 SVM 关系，然后执行相应的操作：
+
|===
| 如果您要 ... | 执行以下操作 ... 


 a| 
初始化 SVM 关系
 a| 
.. 单击 * 操作 * > * 初始化 * 。
+
此时将显示初始化对话框。

.. 单击 * 初始化 * 。




 a| 
更新 SVM 关系
 a| 
.. 单击 * 操作 * > * 更新 * 。
+
此时将显示更新对话框。

.. 单击 * 更新 * 。




 a| 
激活目标 SVM 激活目标 SVM 涉及暂停计划的 SnapMirror 传输，中止任何正在进行的 SnapMirror 传输，中断 SVM 关系以及启动目标 SVM 。
 a| 
.. 单击 * 操作 * > * 激活目标 SVM* 。
+
此时将显示激活目标 SVM 对话框。

.. 选中 * 确定以激活目标 SVM 并中断关系 * 复选框。
.. 单击 * 激活 * 。




 a| 
重新同步源 SVM 中的数据重新同步操作将对 SVM 配置执行重新基线传输。您可以从源 SVM 重新同步以重新建立两个 SVM 之间已断开的关系。重新同步完成后，目标 SVM 将包含与源 SVM 相同的信息，并计划进行进一步更新。
 a| 
.. 单击 * 操作 * > * 从源 SVM* 重新同步。
+
此时将显示从源 SVM 重新同步对话框。

.. 选中 * 确定删除目标 SVM* 中任何较新的数据复选框。
.. 单击 * 重新同步 * 。




 a| 
从目标 SVM 重新同步数据（反向重新同步）您可以从目标 SVM 重新同步，以便在两个 SVM 之间创建新关系。在此操作期间，目标 SVM 将继续提供数据，而源 SVM 将备份目标 SVM 的配置和数据。
 a| 
.. 单击 * 操作 * > * 从目标 SVM 重新同步（反向重新同步） * 。
+
此时将显示从目标 SVM 重新同步（反向重新同步）对话框。

.. 如果 SVM 有多个关系，请选中 * 此 SVM 有多个关系，确定释放到其他关系 * 复选框。
.. 选中 * 确定删除源 SVM* 中的新数据复选框。
.. 单击 * 反向重新同步 * 。




 a| 
重新激活源 SVM 重新激活源 SVM 涉及到保护和重新创建源和目标 SVM 之间的 SVM 关系。如果在创建 SVM 关系时选择了复制源 SVM 配置的选项，则目标 SVM 将停止处理数据。
 a| 
.. 单击 * 操作 * > * 重新激活源 SVM* 。
+
此时将显示重新激活源 SVM 对话框。

.. 单击 * 启动重新激活 * 以启动对目标 SVM 的重新激活。
.. 单击 * 完成 * 。


|===

