---
permalink: online-help-96-97/task_provisioning_storage_by_creating_flash_pool_aggregate_manually.html 
sidebar: sidebar 
keywords: provision, system, manager, storage, create, flash, pool, aggregate, manually, online, help, hdd 
summary: 您可以使用 System Manager 手动创建 Flash Pool 聚合，也可以通过添加 SSD 将现有 HDD 聚合转换为 Flash Pool 聚合。创建新的 HDD 聚合时，您可以为其配置 SSD 缓存并创建 Flash Pool 聚合。 
---
= 使用 System Manager — ONTAP 9.7 及更早版本手动配置存储并创建 Flash Pool 聚合
:icons: font
:imagesdir: ../media/


[role="lead"]
您可以使用 ONTAP System Manager classic （适用于 ONTAP 9.7 及更早版本）手动创建 Flash Pool 聚合，或者通过添加 SSD 将现有 HDD 聚合转换为 Flash Pool 聚合。创建新的 HDD 聚合时，您可以为其配置 SSD 缓存并创建 Flash Pool 聚合。

.开始之前
* 您必须了解有关 Flash Pool 聚合 SSD 层大小和配置的平台专用最佳实践和工作负载专用最佳实践。
* 所有 HDD 都必须处于已置零状态。
* 如果要向聚合添加 SSD ，所有现有 SSD 和专用 SSD 的大小必须相同。


.关于此任务
* 创建 Flash Pool 聚合时，不能使用已分区的 SSD 。
* 如果缓存源为存储池，则无法镜像聚合。
* 从 ONTAP 9.0 开始，您可以创建磁盘大小等于或大于 10 TB 的聚合。
* 如果聚合磁盘的磁盘类型为 FSAS 或 MSATA ，并且磁盘大小等于或大于 10 TB ，则 RAID-TEC 是唯一可用于 RAID 类型的选项。


.步骤
. 使用以下方法之一创建聚合：
+
** 单击 * 应用程序和层 * > * 存储层 * > * 添加聚合 * 。
** 单击 * 存储 * > * 聚合和磁盘 * > * 聚合 * > * 创建 * 。


. 启用 * 手动创建聚合 * 选项以创建聚合。
. 在 * 创建聚合 * 窗口中，指定聚合的名称，磁盘类型以及聚合中 HDD 要包含的磁盘或分区数。
. 如果要镜像聚合，请选中 * 镜像此聚合 * 复选框。
+
对于 MetroCluster 配置，创建未镜像聚合会受到限制。因此，默认情况下， MetroCluster 配置会启用镜像选项。

. 单击 * 对此聚合使用 Flash Pool Cache * 。
. 指定缓存源：
+
|===
| 缓存源选择条件 | 那么 ... 


 a| 
存储池
 a| 
.. 选择 * 存储池 * 作为缓存源。
.. 选择可从中获取缓存的存储池，然后指定缓存大小。
.. 根据需要修改 RAID 类型。




 a| 
专用 SSD
 a| 
.. 选择 * 专用 SSD* 作为缓存源。
.. 选择 SSD 大小以及要包含在聚合中的 SSD 数量。
.. 根据需要修改 RAID 配置：
+
... 单击 * 更改 * 。
... 在更改 RAID 配置对话框中，指定 RAID 类型和 RAID 组大小。
... 单击 * 保存 * 。




|===
. 单击 * 创建 * 。


此时将使用指定的配置创建 Flash Pool 聚合，并将其添加到聚合窗口的聚合列表中。

* 相关信息 *

xref:concept_how_storage_pool_works.adoc[存储池的工作原理]

http://www.netapp.com/us/media/tr-4070.pdf["NetApp 技术报告 4070 ：《 Flash Pool 设计和实施》"^]
