---
permalink: nfs-config-esxi/index.html 
sidebar: sidebar 
keywords: nfs, access, esxi, host, datastores, ontap, volume, configuration, overview, vsc 
summary: 您可以使用 ONTAP 卷为 ESXi 主机快速设置对数据存储库的 NFS 访问。 
---
= 使用 VSC 为 ESXi 配置 NFS 概述
:icons: font
:imagesdir: ../media/


[role="lead"]
您可以使用 ONTAP 卷为 ESXi 主机快速设置对数据存储库的 NFS 访问。

如果要按照以下方式为 ESXi 主机配置对卷的 NFS 访问，应使用此操作步骤：

* 您正在使用运行 ONTAP 9 的集群。
* 您希望使用最佳实践，而不是浏览每个可用选项。
* 您不想阅读大量概念背景信息。
* 您希望使用配置数据存储库并创建卷。
* 您希望使用适用于 ONTAP 9.7 及更早版本的 _Classic_ System Manager UI ，而不是适用于 ONTAP 9.7 及更高版本的 ONTAP System Manager UI 。
+
https://docs.netapp.com/us-en/ontap/["ONTAP System Manager 文档"^]

* 您的数据网络使用默认 IP 空间，默认广播域和默认故障转移组。
+
如果您的数据网络正常运行，则这些默认对象会规定 LIF 在链路出现故障时可以正确地进行故障转移。如果您不使用默认对象，应参见 https://docs.netapp.com/us-en/ontap/networking/index.html["网络管理"] 有关如何配置 LIF 路径故障转移的信息。

* 您希望使用适用于 VMware VAAI 的插件。
+
通过 VMware vStorage APIs for Array Integration （ VAAI ），您可以执行副本卸载和空间预留。适用于 VMware VAAI 的插件使用此功能来提高主机性能，因为操作不需要通过 ESXi 主机，因此可以利用 ONTAP 中节省空间和时间的克隆功能。

+
最佳做法是使用 VMware VAAI 进行数据存储库配置。

* NFS 访问将通过 NFSv3 和 NFSv4 进行，以便与 VMware VAAI 结合使用。


如果此操作步骤不适合您的情况，您应查看以下文档：

* https://docs.netapp.com/us-en/ontap/nfs-admin/index.html["NFS 管理"^]
* http://www.netapp.com/us/media/tr-4067.pdf["NetApp 技术报告 4067 ：《 NFS 最佳实践和实施》"^]
* https://www.netapp.com/pdf.html?item=/media/16328-tr-4668pdf.pdf["NetApp 技术报告 4668 ：《名称服务最佳实践》"^]
* http://www.netapp.com/us/media/tr-4597.pdf["NetApp 技术报告 4597 ：《采用 ONTAP 的 VMware vSphere 》"^]

