---
permalink: fc-config-esxi/index.html 
sidebar: sidebar 
keywords: fc, service, storage, virtual, machine, svm, provision, lun, fc, hba, esx, host, computer, 
summary: 此内容介绍如何在 Storage Virtual Machine 上快速设置 FC 服务，配置 LUN 以及如何使用 ESX 主机计算机上的 FC HBA 将 LUN 用作数据存储库。 
---
= 使用 VSC 为 ESXi 配置 FC 概述
:icons: font
:imagesdir: ../media/


[role="lead"]
此内容介绍如何在 Storage Virtual Machine （ SVM ）上快速设置 FC 服务，配置 LUN 以及如何使用 ESX 主机计算机上的 FC HBA 将 LUN 用作数据存储库。

此内容基于以下假设：

* 您希望使用最佳实践，而不是浏览每个可用选项。
* 您不想阅读大量概念背景信息。
* 您希望使用 System Manager ，而不是 ONTAP 命令行界面或自动化脚本编写工具。
* 您希望使用适用于 ONTAP 9.7 及更早版本的 _Classic_ System Manager UI ，而不是适用于 ONTAP 9.7 及更高版本的 ONTAP System Manager UI 。
+
https://docs.netapp.com/us-en/ontap/["ONTAP System Manager 文档"]

* 您正在使用支持的适用于 VMware vSphere 的 Virtual Storage Console 版本为 ESX 主机配置存储设置并配置数据存储库。
* 您的网络使用 IPv4 地址。
* 您正在 ESXi 5.x 和传统 FC 交换机上使用传统 FC HBA 。
+
此内容不涉及 FCoE 。

* 集群中的每个节点上至少有两个可用的 FC 目标端口。
+
板载 FC 和 UTA2 （也称为 "`CNA` " ）端口以及某些适配器均可配置。配置这些端口会在 ONTAP 命令行界面中完成，此内容不会介绍这些配置。

* 您未配置 FC SAN 启动。
* 您正在主机上创建数据存储库。
+
此内容不包括原始设备映射（ RDM ）磁盘或使用 N 端口 ID 虚拟化（ NPIV ）直接为 VM 提供 FC 。



如果这些假设与您的情况不符，您应查看以下资源：

* https://docs.netapp.com/us-en/ontap/san-admin/index.html["ONTAP 9 SAN 管理"]
* https://docs.netapp.com/us-en/ontap/san-config/index.html["ONTAP 9 SAN 配置"]
* https://docs.netapp.com/vapp-96/topic/com.netapp.doc.vsc-iag/home.html["设备管理"]
* 适用于您的 ESXi 5 版本的 _VMware vSphere Storage_ （可从 VMware 获得）。
+
http://www.vmware.com["VMware"]


